### ISSUE TITLE
Mentions don't change after a user changed his name

### ISSUE THREAD

**Issue by ludovicchabant** [diaspora/diaspora#3526]
- Write a mention post for user A
- Change user A's display name
- The mention still has the old name
##

**Comment by CSammy** [comment]
A future-proof way would be to store simply `@{user@pod.tld}` in the Markdown. The name is, as mentioned, sent anyway in additional JSON objects so the formatter should have no problem.

For old posts, I propose to drop the feature of using the name encoded in the post, because this was never an officially supported feature anyway. Treat all posts the same.

**Comment by cmrd-senya** [comment]
In my opinion a possibility to pick a name in a post while mentioning is a good feature and we shouldn't drop it. Maybe we could make ```@{user@pod.tld}``` the default and in case when there is no name specified pick the name from JSON. Otherwise pick the one from the mention markup.

**Comment by svbergerem** [comment]
@cmrd-senya AFAIK the feature has never been exposed to users. You are able to define the name when mentioning someone but not by using the mention dropdown.

**Comment by cmrd-senya** [comment]
It still works if you write it in a plain markdown and I used it a couple of times myself. Even without adding any UI support it is useful. It can be put in our markdown description and considered as "advanced feature".

**Comment by svbergerem** [comment]
This has been fixed by #7277, #7300, #7302 and #7305.

**Comment by SuperTux88** [comment]
hmm, this is not fixed yet (at least not completely), only when we don't backport mentions anymore (so after #7276 is completed). But it is fixed if we receive a mention with the new syntax (so 0.7 is able to handle it, but doesn't use it yet).  So I'm not sure if we should reopen it and only close it, when we close #7276, of if one issue is enough to track it.
