### ISSUE TITLE
mobile web app - image links issue

### ISSUE THREAD

**Issue by adrianlambert** [diaspora/diaspora#4755]
Clicking on images in posts (except mine) gets me a 404 page.

**Comment by RichKavanagh** [comment]
Didn't I hear recently this has been fixed now?

**Comment by svbergerem** [comment]
I am still able to reproduce this on develop using Firefox 36.

**Comment by npze** [comment]
I still have this issue as well (code is at v0.5.0.1).
I noticed when you browse pictures of the user (via his profile page) on the desktop version, you will not see the images that cause a 404 error on the mobile view. I guess some images are not indexed properly in a way that causes problems in some cases but not all.

**Comment by RichKavanagh** [comment]
Yeah, confirmed this is still an issue. 

Along with the mobile version showing a badly scaled thumbnail (`thumb_large_x`) instead of the `scaled_full_x`

**Comment by npze** [comment]
I agree on the very poor quality of the thumbnails of big pictures in the mobile version.

**Comment by denschub** [comment]
Fixed by #6082.
