### ISSUE TITLE
Link parsing bugs in the new post rendering

### ISSUE THREAD

**Issue by jhass** [diaspora/diaspora#5563]
* [x] Blocking browser for some time: https://social.mrzyx.de/posts/3f6fc4407d93013251b5543d7ed6cc36
* [ ] Not parsing correctly: `http://media.ccc.de/browse/congress/2014/31c3_-_6373_-_en_-_saal_6_-_201412291600_-_the_only_thing_we_know_about_cyberspace_is_that_its_640x480_-_olia_lialina.html`
* [x] Do not autolink IPs or things that look like them, like our version numbers.

**Comment by svbergerem** [comment]
I'll try to fix it this weekend.

**Comment by Flaburgan** [comment]
The stream on d-fr makes Firefox freezes, I guess it is because of that. Any idea how to fix it, or should we revert that? Actually the pod is kinda unusable...

**Comment by svbergerem** [comment]
@Flaburgan That bug is in the linkify plugin. You can uncomment https://github.com/diaspora/diaspora/blob/develop/app/assets/javascripts/app/helpers/text_formatter.js#L73 and the next line. (Please test that first locally!!!) In that case some links won't be recognized anymore (that is why I wrote the plugin which, when activated, will replace the original linkify function) but Firefox shouldn't freeze anymore.

**Comment by svbergerem** [comment]
The second point is also a bug in the commonmark reference implemention: http://spec.commonmark.org/dingus.html?text=http%3A%2F%2Fmedia.ccc.de%2Fbrowse%2Fcongress%2F2014%2F31c3_-_6373_-_en_-_saal_6_-_201412291600_-_the_only_thing_we_know_about_cyberspace_is_that_its_640x480_-_olia_lialina.html

**Comment by millette** [comment]
Not sure if this is related, but the links are also parsed differently in text and when the link is added by diaspora at the bottom of a post (with an optional image). For example I used markdown link format in https://framasphere.org/posts/328933 and the added link is prepended with a parenthesis.

**Comment by jhass** [comment]
@millette that's fixed in #5347 and completely unrelated.

Actually closing this one for now, since #5574 should've fixed the two issues.

**Comment by svbergerem** [comment]
@jhass The second bug is still present. As I said this is an upstream bug. (See https://github.com/markdown-it/markdown-it/issues/38)

**Comment by jhass** [comment]
Upstream doesn't seem overly motivated about fixing this. What should we do about it?

**Comment by AugierLe42e** [comment]
I a first place, maybe disable `_` as a markup for italic and automatically escape any underscore. Would it do the trick until it is solved ?

**Comment by Flaburgan** [comment]
I just entered `0.5.0.0` in a comment in the SPV page and it was turned to a link.

**Comment by millette** [comment]
@Flaburgan looks like an [IPv4 address](https://en.wikipedia.org/wiki/Dot-decimal_notation).

Personally, I don't believe in auto-linking. See the [Public Suffix List](https://publicsuffix.org/list/effective_tld_names.dat) for instance.

**Comment by Flaburgan** [comment]
@millette yeah of course, I'm just wondering if we need to automatically link IPs, that looks... useless.

**Comment by goobertron** [comment]
> I'm just wondering if we need to automatically link IPs, that looks... useless.

I agree this is not a great idea, especially as D* version numbers look like IP addresses!

If someone wants to link to an IP address, they can easily do it using Markdown. We need to allow people to post four-part numbers (such as D* versions) without them being turned into links.

**Comment by jhass** [comment]
We're going to leave the second case as a edge cased to be resolved by users manually using the `<some_url>` syntax.
