### ISSUE TITLE
mention breaks if display name contains markdown

### ISSUE THREAD

**Issue by DeusFigendi** [diaspora/diaspora#7640]
(I think this is a good title to search for)

I recognized Juni Walet juni_walet@pod.geraspora.de could not be mentioned here are two examples:

https://pod.geraspora.de/posts/6994798
https://pod.geraspora.de/posts/9d5492a08f3601351c0f101b0e8ace24

![bildschirmfoto vom 2017-10-13 21-17-11](https://user-images.githubusercontent.com/1711504/31562513-033f7e94-b05c-11e7-8e1a-b8e91f6faca6.png)
![bildschirmfoto vom 2017-10-13 21-16-36](https://user-images.githubusercontent.com/1711504/31562514-035ba02e-b05c-11e7-8364-d5413bed81b0.png)

I did not test it detailed but I'd guess the `[    ]` causes this. I wrote `@{juni_walet@pod.geraspora.de}` so that was converted correctly I think. Probably some escaping is needed?

I'll ask if Juni got notified, but I think so.

**Comment by svbergerem** [comment]
This is the plain text: `@{Juni Walet   [^,..,^]; juni_walet@pod.geraspora.de}`. https://github.com/markdown-it/markdown-it-sup (an inline rule) recognizes `^,..,^` before the mention code is able to see the mention syntax.

**Comment by SuperTux88** [comment]
The `^` is the problem (because it is parsed as markdown), and it will be solved automatically when we remove the server-side backporting for older versions and send the plain new syntax. You can fix this for now when you add a name yourself (so it is already the old syntax and the server doesn't touch it), so for example

**Comment by DeusFigendi** [comment]
> it will be solved automatically when we remove the server-side backporting

I see… but it could also be escaped… `@{Juni Walet [\^,..,\^]; juni_walet@pod.geraspora.de}`

> You can fix this for now when you add a name yourself 

sure, that is a good and simple workaround until it's obsolete.

btw. Juni Walet confirmed she got notified.

**Comment by SuperTux88** [comment]
Fixed by #7788

**Comment by DeusFigendi** [comment]
This bug is back (at least on Geraspora). I saw it a short while ago but I thought it maybe wasn't fixed but now Ravenbird documented it again:

[ ![Ravenbirds post](https://pod.geraspora.de/camo/2dc390229e64a9099bd17fef372c83ed2bb9dd8c/68747470733a2f2f6b697473756e652e636c69636b2f75706c6f6164732f696d616765732f7363616c65645f66756c6c5f65316335356337333835356336383137643062302e6a7067) ](https://pod.geraspora.de/posts/85d453d0cb4301360363386077598c1d)
